title = "Bastien Continsouzas"
baseURL = "https://continsouzas.com/cv-en/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false
defaultContentLanguage = "en"

[params]
address = "Toulouse, FR"
email = "bastien[at]continsouzas[dot]com"
favicon = "/favicon.ico"
firstName = "Bastien"
lastName = "Continsouzas"
phone = "(+33)6.87.26.59.98"
profileImage = "img/profile.png"
showQr = false
showContact = false
showBoards  = false
showCertifications = false
showSocializations = true
showDownload = true
sections = ["skills","experience","education"]

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/continsouzas/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/bcontins/"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
